//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemPrinterDeGacha.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ItemPrinterDeGacha.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1 {
            get {
                object obj = ResourceManager.GetObject("aitem_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_10 {
            get {
                object obj = ResourceManager.GetObject("aitem_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_106 {
            get {
                object obj = ResourceManager.GetObject("aitem_106", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_107 {
            get {
                object obj = ResourceManager.GetObject("aitem_107", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_108 {
            get {
                object obj = ResourceManager.GetObject("aitem_108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_109 {
            get {
                object obj = ResourceManager.GetObject("aitem_109", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_11 {
            get {
                object obj = ResourceManager.GetObject("aitem_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_110 {
            get {
                object obj = ResourceManager.GetObject("aitem_110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1109 {
            get {
                object obj = ResourceManager.GetObject("aitem_1109", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1110 {
            get {
                object obj = ResourceManager.GetObject("aitem_1110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1111 {
            get {
                object obj = ResourceManager.GetObject("aitem_1111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1112 {
            get {
                object obj = ResourceManager.GetObject("aitem_1112", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1113 {
            get {
                object obj = ResourceManager.GetObject("aitem_1113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1114 {
            get {
                object obj = ResourceManager.GetObject("aitem_1114", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1115 {
            get {
                object obj = ResourceManager.GetObject("aitem_1115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1120 {
            get {
                object obj = ResourceManager.GetObject("aitem_1120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1124 {
            get {
                object obj = ResourceManager.GetObject("aitem_1124", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1125 {
            get {
                object obj = ResourceManager.GetObject("aitem_1125", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1126 {
            get {
                object obj = ResourceManager.GetObject("aitem_1126", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1127 {
            get {
                object obj = ResourceManager.GetObject("aitem_1127", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1128 {
            get {
                object obj = ResourceManager.GetObject("aitem_1128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_12 {
            get {
                object obj = ResourceManager.GetObject("aitem_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1253 {
            get {
                object obj = ResourceManager.GetObject("aitem_1253", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1254 {
            get {
                object obj = ResourceManager.GetObject("aitem_1254", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_13 {
            get {
                object obj = ResourceManager.GetObject("aitem_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_14 {
            get {
                object obj = ResourceManager.GetObject("aitem_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_15 {
            get {
                object obj = ResourceManager.GetObject("aitem_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1606 {
            get {
                object obj = ResourceManager.GetObject("aitem_1606", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1842 {
            get {
                object obj = ResourceManager.GetObject("aitem_1842", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1843 {
            get {
                object obj = ResourceManager.GetObject("aitem_1843", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1862 {
            get {
                object obj = ResourceManager.GetObject("aitem_1862", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1863 {
            get {
                object obj = ResourceManager.GetObject("aitem_1863", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1864 {
            get {
                object obj = ResourceManager.GetObject("aitem_1864", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1865 {
            get {
                object obj = ResourceManager.GetObject("aitem_1865", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1866 {
            get {
                object obj = ResourceManager.GetObject("aitem_1866", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1867 {
            get {
                object obj = ResourceManager.GetObject("aitem_1867", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1868 {
            get {
                object obj = ResourceManager.GetObject("aitem_1868", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1869 {
            get {
                object obj = ResourceManager.GetObject("aitem_1869", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1870 {
            get {
                object obj = ResourceManager.GetObject("aitem_1870", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1871 {
            get {
                object obj = ResourceManager.GetObject("aitem_1871", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1872 {
            get {
                object obj = ResourceManager.GetObject("aitem_1872", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1873 {
            get {
                object obj = ResourceManager.GetObject("aitem_1873", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1874 {
            get {
                object obj = ResourceManager.GetObject("aitem_1874", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1875 {
            get {
                object obj = ResourceManager.GetObject("aitem_1875", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1876 {
            get {
                object obj = ResourceManager.GetObject("aitem_1876", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1877 {
            get {
                object obj = ResourceManager.GetObject("aitem_1877", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1878 {
            get {
                object obj = ResourceManager.GetObject("aitem_1878", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1879 {
            get {
                object obj = ResourceManager.GetObject("aitem_1879", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1885 {
            get {
                object obj = ResourceManager.GetObject("aitem_1885", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_1886 {
            get {
                object obj = ResourceManager.GetObject("aitem_1886", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_2 {
            get {
                object obj = ResourceManager.GetObject("aitem_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_221 {
            get {
                object obj = ResourceManager.GetObject("aitem_221", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_222 {
            get {
                object obj = ResourceManager.GetObject("aitem_222", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_223 {
            get {
                object obj = ResourceManager.GetObject("aitem_223", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_229 {
            get {
                object obj = ResourceManager.GetObject("aitem_229", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_23 {
            get {
                object obj = ResourceManager.GetObject("aitem_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_230 {
            get {
                object obj = ResourceManager.GetObject("aitem_230", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_231 {
            get {
                object obj = ResourceManager.GetObject("aitem_231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_232 {
            get {
                object obj = ResourceManager.GetObject("aitem_232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_233 {
            get {
                object obj = ResourceManager.GetObject("aitem_233", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_234 {
            get {
                object obj = ResourceManager.GetObject("aitem_234", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_235 {
            get {
                object obj = ResourceManager.GetObject("aitem_235", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_237 {
            get {
                object obj = ResourceManager.GetObject("aitem_237", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_238 {
            get {
                object obj = ResourceManager.GetObject("aitem_238", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_239 {
            get {
                object obj = ResourceManager.GetObject("aitem_239", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_24 {
            get {
                object obj = ResourceManager.GetObject("aitem_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_240 {
            get {
                object obj = ResourceManager.GetObject("aitem_240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_2401 {
            get {
                object obj = ResourceManager.GetObject("aitem_2401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_2403 {
            get {
                object obj = ResourceManager.GetObject("aitem_2403", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_2404 {
            get {
                object obj = ResourceManager.GetObject("aitem_2404", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_241 {
            get {
                object obj = ResourceManager.GetObject("aitem_241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_242 {
            get {
                object obj = ResourceManager.GetObject("aitem_242", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_243 {
            get {
                object obj = ResourceManager.GetObject("aitem_243", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_244 {
            get {
                object obj = ResourceManager.GetObject("aitem_244", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_245 {
            get {
                object obj = ResourceManager.GetObject("aitem_245", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_246 {
            get {
                object obj = ResourceManager.GetObject("aitem_246", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_247 {
            get {
                object obj = ResourceManager.GetObject("aitem_247", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_248 {
            get {
                object obj = ResourceManager.GetObject("aitem_248", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_2482 {
            get {
                object obj = ResourceManager.GetObject("aitem_2482", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_249 {
            get {
                object obj = ResourceManager.GetObject("aitem_249", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_25 {
            get {
                object obj = ResourceManager.GetObject("aitem_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_250 {
            get {
                object obj = ResourceManager.GetObject("aitem_250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_251 {
            get {
                object obj = ResourceManager.GetObject("aitem_251", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_252 {
            get {
                object obj = ResourceManager.GetObject("aitem_252", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_2549 {
            get {
                object obj = ResourceManager.GetObject("aitem_2549", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_26 {
            get {
                object obj = ResourceManager.GetObject("aitem_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_269 {
            get {
                object obj = ResourceManager.GetObject("aitem_269", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_27 {
            get {
                object obj = ResourceManager.GetObject("aitem_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_272 {
            get {
                object obj = ResourceManager.GetObject("aitem_272", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_273 {
            get {
                object obj = ResourceManager.GetObject("aitem_273", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_277 {
            get {
                object obj = ResourceManager.GetObject("aitem_277", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_28 {
            get {
                object obj = ResourceManager.GetObject("aitem_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_281 {
            get {
                object obj = ResourceManager.GetObject("aitem_281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_29 {
            get {
                object obj = ResourceManager.GetObject("aitem_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_3 {
            get {
                object obj = ResourceManager.GetObject("aitem_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_321 {
            get {
                object obj = ResourceManager.GetObject("aitem_321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_322 {
            get {
                object obj = ResourceManager.GetObject("aitem_322", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_323 {
            get {
                object obj = ResourceManager.GetObject("aitem_323", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_324 {
            get {
                object obj = ResourceManager.GetObject("aitem_324", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_325 {
            get {
                object obj = ResourceManager.GetObject("aitem_325", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_326 {
            get {
                object obj = ResourceManager.GetObject("aitem_326", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_327 {
            get {
                object obj = ResourceManager.GetObject("aitem_327", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_38 {
            get {
                object obj = ResourceManager.GetObject("aitem_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_39 {
            get {
                object obj = ResourceManager.GetObject("aitem_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_4 {
            get {
                object obj = ResourceManager.GetObject("aitem_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_40 {
            get {
                object obj = ResourceManager.GetObject("aitem_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_41 {
            get {
                object obj = ResourceManager.GetObject("aitem_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_45 {
            get {
                object obj = ResourceManager.GetObject("aitem_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_46 {
            get {
                object obj = ResourceManager.GetObject("aitem_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_47 {
            get {
                object obj = ResourceManager.GetObject("aitem_47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_48 {
            get {
                object obj = ResourceManager.GetObject("aitem_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_49 {
            get {
                object obj = ResourceManager.GetObject("aitem_49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_492 {
            get {
                object obj = ResourceManager.GetObject("aitem_492", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_493 {
            get {
                object obj = ResourceManager.GetObject("aitem_493", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_494 {
            get {
                object obj = ResourceManager.GetObject("aitem_494", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_495 {
            get {
                object obj = ResourceManager.GetObject("aitem_495", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_496 {
            get {
                object obj = ResourceManager.GetObject("aitem_496", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_497 {
            get {
                object obj = ResourceManager.GetObject("aitem_497", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_498 {
            get {
                object obj = ResourceManager.GetObject("aitem_498", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_499 {
            get {
                object obj = ResourceManager.GetObject("aitem_499", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_5 {
            get {
                object obj = ResourceManager.GetObject("aitem_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_51 {
            get {
                object obj = ResourceManager.GetObject("aitem_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_52 {
            get {
                object obj = ResourceManager.GetObject("aitem_52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_53 {
            get {
                object obj = ResourceManager.GetObject("aitem_53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_537 {
            get {
                object obj = ResourceManager.GetObject("aitem_537", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_541 {
            get {
                object obj = ResourceManager.GetObject("aitem_541", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_571 {
            get {
                object obj = ResourceManager.GetObject("aitem_571", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_576 {
            get {
                object obj = ResourceManager.GetObject("aitem_576", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_580 {
            get {
                object obj = ResourceManager.GetObject("aitem_580", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_581 {
            get {
                object obj = ResourceManager.GetObject("aitem_581", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_582 {
            get {
                object obj = ResourceManager.GetObject("aitem_582", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_583 {
            get {
                object obj = ResourceManager.GetObject("aitem_583", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_6 {
            get {
                object obj = ResourceManager.GetObject("aitem_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_645 {
            get {
                object obj = ResourceManager.GetObject("aitem_645", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_650 {
            get {
                object obj = ResourceManager.GetObject("aitem_650", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_7 {
            get {
                object obj = ResourceManager.GetObject("aitem_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_795 {
            get {
                object obj = ResourceManager.GetObject("aitem_795", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_796 {
            get {
                object obj = ResourceManager.GetObject("aitem_796", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_8 {
            get {
                object obj = ResourceManager.GetObject("aitem_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_80 {
            get {
                object obj = ResourceManager.GetObject("aitem_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_81 {
            get {
                object obj = ResourceManager.GetObject("aitem_81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_82 {
            get {
                object obj = ResourceManager.GetObject("aitem_82", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_83 {
            get {
                object obj = ResourceManager.GetObject("aitem_83", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_84 {
            get {
                object obj = ResourceManager.GetObject("aitem_84", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_849 {
            get {
                object obj = ResourceManager.GetObject("aitem_849", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_85 {
            get {
                object obj = ResourceManager.GetObject("aitem_85", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_851 {
            get {
                object obj = ResourceManager.GetObject("aitem_851", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_86 {
            get {
                object obj = ResourceManager.GetObject("aitem_86", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_87 {
            get {
                object obj = ResourceManager.GetObject("aitem_87", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_88 {
            get {
                object obj = ResourceManager.GetObject("aitem_88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_89 {
            get {
                object obj = ResourceManager.GetObject("aitem_89", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_9 {
            get {
                object obj = ResourceManager.GetObject("aitem_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_90 {
            get {
                object obj = ResourceManager.GetObject("aitem_90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_91 {
            get {
                object obj = ResourceManager.GetObject("aitem_91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_92 {
            get {
                object obj = ResourceManager.GetObject("aitem_92", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aitem_94 {
            get {
                object obj = ResourceManager.GetObject("aitem_94", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main=ItemPrinterDeGacha
        ///Main.B_AddOne=+1
        ///Main.B_MinusOne=-1
        ///Main.B_Search=Search
        ///Main.CHK_PM2=Successful +/- 2
        ///Main.GB_Time=Time
        ///Main.L_0=0
        ///Main.L_Item=Item:
        ///Main.L_Jobs=Jobs:
        ///Main.L_Max=Max Seconds:
        ///Main.L_Min=Min Seconds:
        ///Main.L_Mode=Mode:
        ///Main.L_N1=-1
        ///Main.L_P1=+1
        ///Main.L_Seconds=Seconds:
        ///Main.L_Seed=Seed:
        ///Main.L_Seek=Seek:
        ///Main.RB_TimeCurrent=Current Time
        ///Main.RB_TimeSpecific=Specific Ticks
        ///Main.Tab_Adjacent=Adjacent
        ///Main.Tab_Ball=Ball
        ///Main.Tab_Bonus=Bonus
        ///Main.Tab_Regular=Regular [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main=Test
        ///Main.B_AddOne=+1
        ///Main.B_MinusOne=-1
        ///Main.B_Search=Search
        ///Main.CHK_PM2=Successful +/- 2
        ///Main.GB_Time=Time
        ///Main.L_0=0
        ///Main.L_Item=Item:
        ///Main.L_Jobs=Jobs:
        ///Main.L_Max=Max Seconds:
        ///Main.L_Min=Min Seconds:
        ///Main.L_Mode=Mode:
        ///Main.L_N1=-1
        ///Main.L_P1=+1
        ///Main.L_Seconds=Seconds:
        ///Main.L_Seed=Seed:
        ///Main.L_Seek=Seek:
        ///Main.RB_TimeCurrent=Current Time
        ///Main.RB_TimeSpecific=Specific Ticks
        ///Main.Tab_Adjacent=Adjacent
        ///Main.Tab_Ball=Ball
        ///Main.Tab_Bonus=Bonus
        ///Main.Tab_Regular=Regular
        ///.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main=ItemPrinterDeGacha
        ///Main.B_AddOne=+1
        ///Main.B_MinusOne=-1
        ///Main.B_Search=Search
        ///Main.CHK_PM2=Successful +/- 2
        ///Main.GB_Time=Time
        ///Main.L_0=0
        ///Main.L_Item=Item:
        ///Main.L_Jobs=Jobs:
        ///Main.L_Max=Max Seconds:
        ///Main.L_Min=Min Seconds:
        ///Main.L_Mode=Mode:
        ///Main.L_N1=-1
        ///Main.L_P1=+1
        ///Main.L_Seconds=Seconds:
        ///Main.L_Seed=Seed:
        ///Main.L_Seek=Seek:
        ///Main.RB_TimeCurrent=Current Time
        ///Main.RB_TimeSpecific=Specific Ticks
        ///Main.Tab_Adjacent=Adjacent
        ///Main.Tab_Ball=Ball
        ///Main.Tab_Bonus=Bonus
        ///Main.Tab_Regular=Regular [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main=ItemPrinterDeGacha
        ///Main.B_AddOne=+1
        ///Main.B_MinusOne=-1
        ///Main.B_Search=Search
        ///Main.CHK_PM2=Successful +/- 2
        ///Main.GB_Time=Time
        ///Main.L_0=0
        ///Main.L_Item=Item:
        ///Main.L_Jobs=Jobs:
        ///Main.L_Max=Max Seconds:
        ///Main.L_Min=Min Seconds:
        ///Main.L_Mode=Mode:
        ///Main.L_N1=-1
        ///Main.L_P1=+1
        ///Main.L_Seconds=Seconds:
        ///Main.L_Seed=Seed:
        ///Main.L_Seek=Seek:
        ///Main.RB_TimeCurrent=Current Time
        ///Main.RB_TimeSpecific=Specific Ticks
        ///Main.Tab_Adjacent=Adjacent
        ///Main.Tab_Ball=Ball
        ///Main.Tab_Bonus=Bonus
        ///Main.Tab_Regular=Regular [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main=ItemPrinterDeGacha
        ///Main.B_AddOne=+1
        ///Main.B_MinusOne=-1
        ///Main.B_Search=Search
        ///Main.CHK_PM2=Successful +/- 2
        ///Main.GB_Time=Time
        ///Main.L_0=0
        ///Main.L_Item=Item:
        ///Main.L_Jobs=Jobs:
        ///Main.L_Max=Max Seconds:
        ///Main.L_Min=Min Seconds:
        ///Main.L_Mode=Mode:
        ///Main.L_N1=-1
        ///Main.L_P1=+1
        ///Main.L_Seconds=Seconds:
        ///Main.L_Seed=Seed:
        ///Main.L_Seek=Seek:
        ///Main.RB_TimeCurrent=Current Time
        ///Main.RB_TimeSpecific=Specific Ticks
        ///Main.Tab_Adjacent=Adjacent
        ///Main.Tab_Ball=Ball
        ///Main.Tab_Bonus=Bonus
        ///Main.Tab_Regular=Regular [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main=ItemPrinterDeGacha
        ///Main.B_AddOne=+1
        ///Main.B_MinusOne=-1
        ///Main.B_Search=Search
        ///Main.CHK_PM2=Successful +/- 2
        ///Main.GB_Time=Time
        ///Main.L_0=0
        ///Main.L_Item=Item:
        ///Main.L_Jobs=Jobs:
        ///Main.L_Max=Max Seconds:
        ///Main.L_Min=Min Seconds:
        ///Main.L_Mode=Mode:
        ///Main.L_N1=-1
        ///Main.L_P1=+1
        ///Main.L_Seconds=Seconds:
        ///Main.L_Seed=Seed:
        ///Main.L_Seek=Seek:
        ///Main.RB_TimeCurrent=Current Time
        ///Main.RB_TimeSpecific=Specific Ticks
        ///Main.Tab_Adjacent=Adjacent
        ///Main.Tab_Ball=Ball
        ///Main.Tab_Bonus=Bonus
        ///Main.Tab_Regular=Regular [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main=ItemPrinterDeGacha
        ///Main.B_AddOne=+1
        ///Main.B_MinusOne=-1
        ///Main.B_Search=Search
        ///Main.CHK_PM2=Successful +/- 2
        ///Main.GB_Time=Time
        ///Main.L_0=0
        ///Main.L_Item=Item:
        ///Main.L_Jobs=Jobs:
        ///Main.L_Max=Max Seconds:
        ///Main.L_Min=Min Seconds:
        ///Main.L_Mode=Mode:
        ///Main.L_N1=-1
        ///Main.L_P1=+1
        ///Main.L_Seconds=Seconds:
        ///Main.L_Seed=Seed:
        ///Main.L_Seek=Seek:
        ///Main.RB_TimeCurrent=Current Time
        ///Main.RB_TimeSpecific=Specific Ticks
        ///Main.Tab_Adjacent=Adjacent
        ///Main.Tab_Ball=Ball
        ///Main.Tab_Bonus=Bonus
        ///Main.Tab_Regular=Regular [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main=ItemPrinterDeGacha
        ///Main.B_AddOne=+1
        ///Main.B_MinusOne=-1
        ///Main.B_Search=Search
        ///Main.CHK_PM2=Successful +/- 2
        ///Main.GB_Time=Time
        ///Main.L_0=0
        ///Main.L_Item=Item:
        ///Main.L_Jobs=Jobs:
        ///Main.L_Max=Max Seconds:
        ///Main.L_Min=Min Seconds:
        ///Main.L_Mode=Mode:
        ///Main.L_N1=-1
        ///Main.L_P1=+1
        ///Main.L_Seconds=Seconds:
        ///Main.L_Seed=Seed:
        ///Main.L_Seek=Seek:
        ///Main.RB_TimeCurrent=Current Time
        ///Main.RB_TimeSpecific=Specific Ticks
        ///Main.Tab_Adjacent=Adjacent
        ///Main.Tab_Ball=Ball
        ///Main.Tab_Bonus=Bonus
        ///Main.Tab_Regular=Regular [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main=ItemPrinterDeGacha
        ///Main.B_AddOne=+1
        ///Main.B_MinusOne=-1
        ///Main.B_Search=Search
        ///Main.CHK_PM2=Successful +/- 2
        ///Main.GB_Time=Time
        ///Main.L_0=0
        ///Main.L_Item=Item:
        ///Main.L_Jobs=Jobs:
        ///Main.L_Max=Max Seconds:
        ///Main.L_Min=Min Seconds:
        ///Main.L_Mode=Mode:
        ///Main.L_N1=-1
        ///Main.L_P1=+1
        ///Main.L_Seconds=Seconds:
        ///Main.L_Seed=Seed:
        ///Main.L_Seek=Seek:
        ///Main.RB_TimeCurrent=Current Time
        ///Main.RB_TimeSpecific=Specific Ticks
        ///Main.Tab_Adjacent=Adjacent
        ///Main.Tab_Ball=Ball
        ///Main.Tab_Bonus=Bonus
        ///Main.Tab_Regular=Regular [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zh2 {
            get {
                return ResourceManager.GetString("lang_zh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ErrorMinMax&quot;: &quot;Min must be less than or equal to Max.&quot;,
        ///  &quot;ErrorNoItem&quot;: &quot;No item specified&quot;,
        ///  &quot;ErrorInvalidSearchCriteria&quot;: &quot;Invalid search criteria.&quot;,
        ///  &quot;F0_Count&quot;: &quot;Count: {0}&quot;,
        ///  &quot;F1_Time&quot;: &quot;Time: {0}&quot;,
        ///  &quot;F1_Seed&quot;: &quot;Seed: {0}&quot;,
        ///  &quot;F2_CountItem&quot;: &quot;x{0} {1}&quot;,
        ///  &quot;F3_ModeAtTimeSeed&quot;: &quot;{0} @ {1} -- {2}&quot;
        ///}.
        /// </summary>
        internal static string message_de {
            get {
                return ResourceManager.GetString("message_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ErrorMinMax&quot;: &quot;Min must be less than or equal to Max.&quot;,
        ///  &quot;ErrorNoItem&quot;: &quot;No item specified&quot;,
        ///  &quot;ErrorInvalidSearchCriteria&quot;: &quot;Invalid search criteria.&quot;,
        ///  &quot;F1_Count&quot;: &quot;CountX: {0}&quot;,
        ///  &quot;F1_Time&quot;: &quot;Time: {0}&quot;,
        ///  &quot;F1_Seed&quot;: &quot;Seed: {0}&quot;,
        ///  &quot;F2_CountItem&quot;: &quot;x{0} {1}&quot;,
        ///  &quot;F3_ModeAtTimeSeed&quot;: &quot;{0} @ {1} -- {2}&quot;
        ///}.
        /// </summary>
        internal static string message_en {
            get {
                return ResourceManager.GetString("message_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ErrorMinMax&quot;: &quot;Min must be less than or equal to Max.&quot;,
        ///  &quot;ErrorNoItem&quot;: &quot;No item specified&quot;,
        ///  &quot;ErrorInvalidSearchCriteria&quot;: &quot;Invalid search criteria.&quot;,
        ///  &quot;F0_Count&quot;: &quot;Count: {0}&quot;,
        ///  &quot;F1_Time&quot;: &quot;Time: {0}&quot;,
        ///  &quot;F1_Seed&quot;: &quot;Seed: {0}&quot;,
        ///  &quot;F2_CountItem&quot;: &quot;x{0} {1}&quot;,
        ///  &quot;F3_ModeAtTimeSeed&quot;: &quot;{0} @ {1} -- {2}&quot;
        ///}.
        /// </summary>
        internal static string message_es {
            get {
                return ResourceManager.GetString("message_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ErrorMinMax&quot;: &quot;Min must be less than or equal to Max.&quot;,
        ///  &quot;ErrorNoItem&quot;: &quot;No item specified&quot;,
        ///  &quot;ErrorInvalidSearchCriteria&quot;: &quot;Invalid search criteria.&quot;,
        ///  &quot;F0_Count&quot;: &quot;Count: {0}&quot;,
        ///  &quot;F1_Time&quot;: &quot;Time: {0}&quot;,
        ///  &quot;F1_Seed&quot;: &quot;Seed: {0}&quot;,
        ///  &quot;F2_CountItem&quot;: &quot;x{0} {1}&quot;,
        ///  &quot;F3_ModeAtTimeSeed&quot;: &quot;{0} @ {1} -- {2}&quot;
        ///}.
        /// </summary>
        internal static string message_fr {
            get {
                return ResourceManager.GetString("message_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ErrorMinMax&quot;: &quot;Min must be less than or equal to Max.&quot;,
        ///  &quot;ErrorNoItem&quot;: &quot;No item specified&quot;,
        ///  &quot;ErrorInvalidSearchCriteria&quot;: &quot;Invalid search criteria.&quot;,
        ///  &quot;F0_Count&quot;: &quot;Count: {0}&quot;,
        ///  &quot;F1_Time&quot;: &quot;Time: {0}&quot;,
        ///  &quot;F1_Seed&quot;: &quot;Seed: {0}&quot;,
        ///  &quot;F2_CountItem&quot;: &quot;x{0} {1}&quot;,
        ///  &quot;F3_ModeAtTimeSeed&quot;: &quot;{0} @ {1} -- {2}&quot;
        ///}.
        /// </summary>
        internal static string message_it {
            get {
                return ResourceManager.GetString("message_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ErrorMinMax&quot;: &quot;Min must be less than or equal to Max.&quot;,
        ///  &quot;ErrorNoItem&quot;: &quot;No item specified&quot;,
        ///  &quot;ErrorInvalidSearchCriteria&quot;: &quot;Invalid search criteria.&quot;,
        ///  &quot;F0_Count&quot;: &quot;Count: {0}&quot;,
        ///  &quot;F1_Time&quot;: &quot;Time: {0}&quot;,
        ///  &quot;F1_Seed&quot;: &quot;Seed: {0}&quot;,
        ///  &quot;F2_CountItem&quot;: &quot;x{0} {1}&quot;,
        ///  &quot;F3_ModeAtTimeSeed&quot;: &quot;{0} @ {1} -- {2}&quot;
        ///}.
        /// </summary>
        internal static string message_ja {
            get {
                return ResourceManager.GetString("message_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ErrorMinMax&quot;: &quot;Min must be less than or equal to Max.&quot;,
        ///  &quot;ErrorNoItem&quot;: &quot;No item specified&quot;,
        ///  &quot;ErrorInvalidSearchCriteria&quot;: &quot;Invalid search criteria.&quot;,
        ///  &quot;F0_Count&quot;: &quot;Count: {0}&quot;,
        ///  &quot;F1_Time&quot;: &quot;Time: {0}&quot;,
        ///  &quot;F1_Seed&quot;: &quot;Seed: {0}&quot;,
        ///  &quot;F2_CountItem&quot;: &quot;x{0} {1}&quot;,
        ///  &quot;F3_ModeAtTimeSeed&quot;: &quot;{0} @ {1} -- {2}&quot;
        ///}.
        /// </summary>
        internal static string message_ko {
            get {
                return ResourceManager.GetString("message_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ErrorMinMax&quot;: &quot;Min must be less than or equal to Max.&quot;,
        ///  &quot;ErrorNoItem&quot;: &quot;No item specified&quot;,
        ///  &quot;ErrorInvalidSearchCriteria&quot;: &quot;Invalid search criteria.&quot;,
        ///  &quot;F0_Count&quot;: &quot;Count: {0}&quot;,
        ///  &quot;F1_Time&quot;: &quot;Time: {0}&quot;,
        ///  &quot;F1_Seed&quot;: &quot;Seed: {0}&quot;,
        ///  &quot;F2_CountItem&quot;: &quot;x{0} {1}&quot;,
        ///  &quot;F3_ModeAtTimeSeed&quot;: &quot;{0} @ {1} -- {2}&quot;
        ///}.
        /// </summary>
        internal static string message_zh {
            get {
                return ResourceManager.GetString("message_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ErrorMinMax&quot;: &quot;Min must be less than or equal to Max.&quot;,
        ///  &quot;ErrorNoItem&quot;: &quot;No item specified&quot;,
        ///  &quot;ErrorInvalidSearchCriteria&quot;: &quot;Invalid search criteria.&quot;,
        ///  &quot;F0_Count&quot;: &quot;Count: {0}&quot;,
        ///  &quot;F1_Time&quot;: &quot;Time: {0}&quot;,
        ///  &quot;F1_Seed&quot;: &quot;Seed: {0}&quot;,
        ///  &quot;F2_CountItem&quot;: &quot;x{0} {1}&quot;,
        ///  &quot;F3_ModeAtTimeSeed&quot;: &quot;{0} @ {1} -- {2}&quot;
        ///}.
        /// </summary>
        internal static string message_zh2 {
            get {
                return ResourceManager.GetString("message_zh2", resourceCulture);
            }
        }
    }
}
